spring:
  application:
    name: pass-batch
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:h2:mem:mydb
    username: pass_local
    password: passlocal
    driver-class-name: org.h2.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 20

#  batch:
#    jdbc:
#      initialize-schema: always